<?php
	return [
		'clientId'           => env("NIBE_CLIENT_ID"),
		'clientSecret'       => env("NIBE_CLIENT_SECRET"),
		'systemId'           => env("NIBE_SYSTEM_ID"),
		'deviceId'           => env("NIBE_DEVICE_ID"),
		'tokenUrl'           => "https://api.myuplink.com/oauth/token",
		'functionUrl'        => "https://api.myuplink.com/v2",
		'allowBoosts'        => env("NIBE_BOOSTS_ALLOWED", false),
		'boostMaxCost'       => env("NIBE_BOOSTS_MAX_COST", 10),
		'cheapMode'          => env("NIBE_CHEAP_MODE", false),
		'cheapModeOffsetMax' => env("NIBE_CHEAP_MODE_OFFSET_MAXIMUM", -4),
		'coolingStartTemp'   => env("NIBE_COOLING_START_TEMP", 24),
		'dmOverride'         => env("NIBE_DM_OVERRIDE", false),
		'dmTarget'           => env("NIBE_DM_TARGET", -180),
		'dmTargetOff'        => env("NIBE_DM_TARGET_OFF", 30),
		'dmTargetOffTemp'    => env("NIBE_DM_TARGET_OFF_TEMP", 12),
		'dmTargetBoost'      => env("NIBE_DM_TARGET_BOOST", -360),
		'dmTargetBoostTemp'  => env("NIBE_DM_TARGET_BOOST_TEMP", 3),
		'dmTargetCooling'    => env("NIBE_DM_TARGET_COOLING", 75),
		'loadCompensationOn' => env("NIBE_LOAD_COMPENSATION_ON", true),
		'loadCompTempOff'    => env("NIBE_LOAD_COMP_TEMP_OFF", 22),
		'minutesToDm'        => env("NIBE_MINUTES_TO_DM", 30),
		'offsetFactor'       => env("NIBE_OFFSET_FACTOR", 2),
		'offsetMinimum'      => env("NIBE_OFFSET_MINIMUM", -10),
		'offsetMaximum'      => env("NIBE_OFFSET_MAXIMUM", 10),
		'offsetMaxInt'       => env("NIBE_OFFSET_MAXIMUM_INTERMITTENT", 0),
		'runLevel1Temp'      => env("NIBE_RUN_LEVEL_1_TEMP", 12),
		'runLevel2Temp'      => env("NIBE_RUN_LEVEL_2_TEMP", 9),
		'tempFreqMin'        => env("NIBE_TEMP_FREQ_MIN", 6),
	];
